### ISSUE TITLE
good idea

### ISSUE THREAD

**Issue by vnues** [flut1/webpack-on-demand#1]
Hello, I looked at your warehouse. It’s a good idea, but it will also create a lot of small files. If the project is large, a lot of files will be created. This kind of cures the symptoms and not the root cause. Although the created files can be placed in the worker,but...

**Comment by flut1** [comment]
Thanks for the feedback

I'm not sure if I 100% understand your comment, but just to reply to the creation of lots of files:
This project is only intended to be used for development. It shouldn't be used to build code that you ship in production.
